### ISSUE TITLE
Two empty brace pairs at end of command([] [])

### ISSUE THREAD

**Issue by astridjerald** [bramus/monolog-colored-line-formatter#14]
Hello There,
I am not too sure of why do we have two empty brace pairs at the end of the command([] []). I'm guessing it is to include context array but it would be cleaner if they were not to be present.

**Comment by aldenw** [comment]
@astridjerald you can remove these using the 5th parameter of the constructor `$ignoreEmptyContextAndExtra`, setting that to be true.

**Comment by astridjerald** [comment]
Thanks @aldenw
