### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by BenjaminHoegh** [bramus/monolog-colored-line-formatter#9]
I have install it and did what you told in the documentation, but when I open the .log file I can't see any colours

**Comment by thexpand** [comment]
@BenjaminHoegh This is because the colors are display in the CLI, while printing the output. It is completely normal not to see any colors when you open the .log file.

**Comment by bramus** [comment]
To see the colors, cat your file on the CLI:

````
cd /path/to/logs/
cat logfile.log
````
